import '@img/room-details.jpg'
import '@img/room-details-2.jpg'
import '@img/room-details-3.jpg'
import '@fortawesome/fontawesome-free/css/all.min.css'

import '@style/global.scss'
import '@blocks/logo/logo.scss'
import '@blocks/button/button.scss'
import '@blocks/sign-in/sign-in.scss'
import '@blocks/nav/nav.scss'
import '@blocks/nav/nav.js'
import '@blocks/header/header.scss'
import '@blocks/card/card.scss'
import '@blocks/room-info-item/room-info-item.scss'
import '@blocks/like-button/like-button.scss'
import '@blocks/review/review.scss'
// import '@blocks/range-slider/range-slider.scss'
// import '@blocks/expandable-list/expandable-list.scss'
// import '@blocks/checkbox/checkbox.scss'
// import '@blocks/room-card/room-card.js'
// import '@blocks/room-card/room-card.scss'
// import '@blocks/rate/rate.scss'
// import '@blocks/pagination/pagination.scss'
import '@blocks/field/field.scss'
import '@blocks/copyright-bar/copyright-bar.scss'
import '@blocks/footer/footer.scss'
import '@pages/room-details/room-details.scss'