// import '@img/room-details.jpg'
// import '@img/room-details-2.jpg'
// import '@img/room-details-3.jpg'
// import '@img/image.png'
// import '@img/image_4.png'
import '@fortawesome/fontawesome-free/css/all.min.css'

import '@style/global.scss'
import '@blocks/logo/logo.scss'
import '@blocks/button/button.scss'
import '@blocks/sign-in/sign-in.scss'
import '@blocks/nav/nav.scss'
import '@blocks/nav/nav.js'
import '@blocks/header/header.scss'
import '@blocks/card/card.scss'
import '@blocks/room-info-item/room-info-item.scss'
import '@blocks/like-button/like-button.scss'
import '@blocks/review/review.scss'
import '@blocks/bullet-list/bullet-list.scss'
import '@blocks/pie/pie.scss'
import '@blocks/pie/pie.js'
import '@blocks/field/field.scss'
import '@blocks/copyright-bar/copyright-bar.scss'
import '@blocks/footer/footer.scss'
import '@pages/room-details/room-details.scss'