import '@fortawesome/fontawesome-free/css/all.min.css'

import '@style/global.scss'
import '@blocks/logo/logo.scss'
import '@blocks/button/button.scss'
import '@blocks/sign-in/sign-in.scss'
import '@blocks/nav/nav.scss'
import '@blocks/nav/nav.js'
import '@blocks/header/header.scss'
import '@blocks/range-slider/range-slider.scss'
import '@blocks/expandable-list/expandable-list.scss'
import '@blocks/checkbox/checkbox.scss'
import '@blocks/field/field.scss'
import '@blocks/copyright-bar/copyright-bar.scss'
import '@blocks/footer/footer.scss'
import '@pages/search-room/search-room.scss'